baseURL = 'https://docs.exray.dev/'
languageCode = 'en-us'
title = 'Side-Eye Debugger'

[deployment]

[[deployment.targets]]
# An arbitrary name for this target.
URL = "s3://exray-docs?region=us-east-2"
name = "production"

cloudFrontDistributionID = "E2EIHKCAY2IJSJ"

[params]
BookSection = '*'
